import React from 'react';
import PropTypes from 'prop-types'; // Import PropTypes

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

// PropTypes validation for the `children` prop
RootLayout.propTypes = {
  children: PropTypes.node.isRequired, // `children` must be a React node (e.g., elements, strings, numbers)
};
