name: CI/CD Pipeline for Next.js App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Run tests
      run: npm run test

    - name: Build Docker image
      run: docker build -t project-devops-uvt .

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Push Docker image to Azure Container Registry
      run: |
        docker tag project-devops-uvt:latest ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/project-devops-uvt:latest
        docker push ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/project-devops-uvt:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Azure CLI setup
      uses: azure/setup-azure-cli@v1

    - name: Login to Azure
      run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Deploy to Azure Web App (App Service)
      run: |
        az webapp create --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --plan ${{ secrets.AZURE_PLAN_NAME }} --name project-devops-uvt --deployment-container-image-name ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/project-devops-uvt:latest
