name: Build and Deploy Next.js App to Azure

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry (ACR)
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_ACR_SERVER }}
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: Build Docker image for Next.js app
      run: |
        docker build -t nextjs-app .
        docker tag nextjs-app:latest ${{ secrets.AZURE_ACR_SERVER }}/nextjs-app:latest

    - name: Push Docker image to ACR
      run: |
        docker push ${{ secrets.AZURE_ACR_SERVER }}/nextjs-app:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mp2l-devops'
        images: ${{ secrets.AZURE_ACR_SERVER }}/nextjs-app:latest
