name: Build and deploy Node.js app to Azure Web App - mp2l-devops

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: |
          docker build -t my-node-app .

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Push Docker image to Azure Container Registry
        run: |
          docker tag my-node-app ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/my-node-app:latest
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/my-node-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FCD7B61463EF457F91AAD146F4B1C4B1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_48474C7A22FB45FA9A942FEC929A64F1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9BAB63352C7449A78B7DE9B322474C2D }}

      - name: 'Deploy Docker container to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-container-deploy@v2
        with:
          app-name: 'mp2l-devops'
          slot-name: 'Production'
          images: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/my-node-app:latest
